### ISSUE TITLE
Does this repo provide model to handle seasonality?? 

### ISSUE THREAD

**Issue by chhavibansal** [Sqooba/scala-timeseries-lib#6]
I am talking about SARIMA, or HOLT-WINTER equivalent. A fast reply would be highly appreciated.

**Comment by Shastick** [comment]
Hello @chhavibansal, this library does not offer any features related to time-series analysis: it's goal is solely for manipulating this kind of data. 

Thus, I'm afraid, it won't help you in any way for seasonality related questions.

**Comment by chhavibansal** [comment]
Thank you @Shastick  This is helpful. Just a quick one, have you worked with any library giving good forecast in Scala for data with seasonality?

**Comment by Shastick** [comment]
I don't know of any: the only one I'm aware of that offers some analytical capabilities would be https://github.com/carldata/timeseries though they don't mention seasonality at all.

**Comment by chhavibansal** [comment]
Thank you @Shastick
